# Generated by Django 4.2.4 on 2023-10-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_course_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
